### ISSUE TITLE
install instructions needed in readme. 

### ISSUE THREAD

**Issue by andykillen** [beyonk-adventures/svelte-social-auth#11]
using
````npm i @beyonk/svelte-social-auth````
works
but
````npm i beyonk-adventures/svelte-social-auth````
does not work, even though it installs.  it complains 
Error: Cannot find module 'node_modules/@beyonk/svelte-social-auth/index.js'.

I hereby suggest you add the install instructions to the readme.md

**Comment by antony** [comment]
Hi @andykillen - happy to accept a PR for this. I'm not sure why anybody would install it any other way than the first way you've documented however.

**Comment by andykillen** [comment]
It's that because this repo has higher search result placement (#2) than the npm version of this information, which is not on the first page on my results. Incidentally the #3 result is the "made with svelte" site, which again link to this Git repo and not npm. 

It is common to just grab the path from the url on github and it work for npm.  Without install instructions, or whatever, people will get it wrong.

**Comment by antony** [comment]
I would've thought the code samples in the readme would be enough to indicate the presence of an npm package.

I'm going up disagree that it's common for people to expect a github url to resolve to an npm package, it would depend on both the scope and package name being an exact match for the github org and repository name. if you are doing that I would recommend you stop, since the likely scenario is that you end up installing the package from github which will result in your application depending on the master branch (and receiving the latest master upon each install). This is **incredibly** dangerous, and wildly unpredictable, and for compiled packages it just won't work.

I'll add some more explicit instructions to the repository unless you are willing to open a PR to do so before I get a chance?

Thanks for spotting this.
